CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_number INT NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  owner VARCHAR(70) DEFAULT NULL,
  dateIn DATETIME DEFAULT NULL,
  dateOut DATETIME DEFAULT NULL,
  UNIQUE KEY uq_rooms_room_number (room_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;